// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2BrkbrLpe3eD4nuKczp9mCNb-gOawei0',
    appId: '1:856162467039:web:0a52642b1c3df73e3ffd6a',
    messagingSenderId: '856162467039',
    projectId: 'adan-russia',
    authDomain: 'adan-russia.firebaseapp.com',
    storageBucket: 'adan-russia.appspot.com',
    measurementId: 'G-L5PEJQVHKY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaosk7q_kAfn1AyUxHSCccy9uY1ebOiY8',
    appId: '1:856162467039:android:823b9417427370fc3ffd6a',
    messagingSenderId: '856162467039',
    projectId: 'adan-russia',
    storageBucket: 'adan-russia.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9xpQXh3KSy-LRkzDRjs3jtbkNMxMJX_I',
    appId: '1:856162467039:ios:65360a4199d660753ffd6a',
    messagingSenderId: '856162467039',
    projectId: 'adan-russia',
    storageBucket: 'adan-russia.appspot.com',
    iosBundleId: 'com.example.adanRussia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9xpQXh3KSy-LRkzDRjs3jtbkNMxMJX_I',
    appId: '1:856162467039:ios:a2c5e1c225654cec3ffd6a',
    messagingSenderId: '856162467039',
    projectId: 'adan-russia',
    storageBucket: 'adan-russia.appspot.com',
    iosBundleId: 'com.example.adanRussia.RunnerTests',
  );
}
